services:
  db:
    container_name: postgres_fastapi
    image: postgres
    env_file:
      - ./server/.env
    volumes:
      - ./postgres_db:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    restart: unless-stopped
    networks:
      - fast_api

  app:
    container_name: recep
    build:
      context: ./server
    env_file:
      - ./server/.env
    volumes:
      - ./server:/server
    ports:
      - "9991:8000"
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - fast_api

networks:
  fast_api:
    driver: bridge
